# Generated by Django 4.2.18 on 2025-01-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
