# Generated by Django 4.2.18 on 2025-01-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
    ]
