# Generated by Django 4.2.18 on 2025-01-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
