# Generated by Django 4.2.18 on 2025-01-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('author', 'post')},
        ),
    ]
