# Generated by Django 4.2.18 on 2025-01-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_answer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
